version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: meduser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: medcheck
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: